name: staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./apps/backend
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ./apps/backend/target/
            ~/.cargo
            !./apps/backend/target/debug
          key: backend-dependencies
      # - name: Cargo install
      #   run: cargo install sea-orm-cli
    #   - name: Clippy install
    #     run: rustup component add clippy
      - name: Debug
        run: |
          ls target
          pwd
          stat -c %Y Dockerfile
      - name: Build Binary
        working-directory: apps/backend
        run: cargo build
      # - name: Run backend
      #   run: |
      #     cd apps/backend
      #     cargo run &
      # - name: Run frontend
      #   run: |
      #     cd apps/frontend
      #     yarn install
      #     yarn dev &
      # - name: Run frontend test
      #   run: |
      #     cd apps/frontend
      #     yarn test
    #       ls -la apps/backend/
    #       cat apps/backend/.dockerignore
    #       sed -i '$d' apps/backend/.dockerignore
    #       ls -la apps/backend/
    #       cat apps/backend/.dockerignore
      # - name: Build release
      #   run: |
      #     cd apps/backend
      #     cargo build --release
    #   - name: Build Docker Image
    #     run: docker build --platform linux/amd64 -f ./Dockerfile . -t test
    #   - name: Debug docker
    #     run: docker system df
