name: staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
    #   - name: Cargo install
    #     shell: bash
    #     run: cargo install sea-orm-cli cargo-llvm-cov cargo-nextest
    #   - name: Clippy install
    #     shell: bash
    #     run: rustup component add clippy
    #   - name: Debug
    #     shell: bash
    #     run: |
    #       docker images
    #   - name: Build Binary
    #     shell: bash
    #     run: cargo build --release
      - name: Edit .dockerignore
        shell: bash
        run: |
          sed '$d' .dockerignore .dockerignore_tmp
          rm .dockerignore
          mv .dockerignore_tmp .dockerignore
          cat .dockerignore
      - name: Cache
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: apt-install
      - name: Build Docker Image
        shell: bash
        run: docker build --platform linux/amd64 -f ./Dockerfile . -t test
