name: staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
    #   - name: Cargo install
    #     shell: bash
    #     run: cargo install sea-orm-cli
    #   - name: Clippy install
    #     shell: bash
    #     run: rustup component add clippy
    #   - name: Debug
    #     shell: bash
    #     run: |
    #       docker images
    #   - name: Build Binary
    #     shell: bash
    #     run: cargo build --release
      - name: Edit .dockerignore
        shell: bash
        run: |
          ls -la apps/backend/
          cat apps/backend/.dockerignore
          sed -i '' '$d' apps/backend/.dockerignore
          ls -la apps/backend/
          cat apps/backend/.dockerignore
      - name: Cache
        uses: actions/cache@v4
        with:
          path: apps/backend/target
          key: ${{ runner.os }}-${{ hashFiles('apps/backend/Cargo.lock') }}
      # - name: Build release
      #   shell: bash
      #   run: |
      #     cd apps/backend
      #     cargo build --release
    #   - name: Build Docker Image
    #     shell: bash
    #     run: docker build --platform linux/amd64 -f ./Dockerfile . -t test
    #   - name: Debug docker
    #     shell: bash
    #     run: docker system df
